name: CI
on:
  create:
    tags:
      - v*
  workflow_dispatch:
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Artifact
        uses: actions/upload-artifact@v2.3.1
        with:
          name: mortuary.asl
          path: ./mortuary.asl

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: mortuary.asl